# Generated by Django 4.2.6 on 2023-11-11 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_category_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(name="job", options={"ordering": ["-id"]},),
        migrations.CreateModel(
            name="jobApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "resume",
                    models.FileField(
                        help_text="please upload your latest resume",
                        upload_to="resumes/",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(help_text="please write your", max_length=500),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="please enter github profile url",
                        null=True,
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="please enter Linkedin profile url",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Apply_job",
                        to="job.job",
                    ),
                ),
            ],
        ),
    ]
